Show total downloads (#29)
* wip

* wip

* wip

* wip

* wip

* wip

* wip

* wip

* wip

* wip

* wip

* wip

* wip

* wip

* wip

* wip

* wip

* wip

* wip

* wip

* wip

* wip

* secret

* wip

* wip

* wip

* wip

* wip

* wip

* wip

* wip

* wi

* wip

* wip

* wip

* wip

* default disabled

* wip

* wip

* wip

* wip

* wip

* wip

* qip

* wip

* wip

* wip

* wip

* wip

* wip

* wip

* wip probs fine?

* windows

* installer tests

* wip

* wip

* wip

* fmt

* wip

* wip

* wip

* wip

* wip

* wip

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -20,9 +20,18 @@ jobs:
         with:
           go-version: stable
 
+      - name: Check required secrets
+        run: |
+          if [ -z "${{ secrets.POSTHOG_API_KEY }}" ]; then
+            echo "Error: POSTHOG_API_KEY secret is not set"
+            exit 1
+          fi
+
       - uses: goreleaser/goreleaser-action@v6
         with:
           version: "~> v2"
           args: release --clean
         env:
           GITHUB_TOKEN: ${{ secrets.HOMEBREW_GITHUB_PAT }}
+          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
+          POSTHOG_API_HOST: https://us.i.posthog.com
